name = "TestPackage"
uuid = "e8bf0d59-3f65-4626-961c-93d33f0e8cae"
authors = ["Patrick Jaap <patrick.jaap@wias-berlin.de>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
